stages:
  - build
  - test      # SAST & Code Analysis
  - security  # Container Scanning
  - release   # Push to Registry
  - deploy    # Deploy to Prod

variables:
  DOCKER_DRIVER: overlay2
  # Nom de l'image complet avec le commit SHA pour l'unicité temporaire
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

# --- STAGE: BUILD ---
build_image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Docker Image..."
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG # Push temporaire pour les scans
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID

# --- STAGE: TEST (SAST) ---
# 1. SonarQube Analysis
sonarqube-check:
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true # On permet l'échec pour le TP, mais en prod = false
  only:
    - main
    - merge_requests

# 2. Semgrep (SAST léger et rapide)
semgrep-sast:
  stage: test
  image: returntocorp/semgrep
  script:
    - semgrep ci --config=p/php --config=p/security-audit --config=p/secrets
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID

# --- STAGE: SECURITY (Container Scanning) ---
trivy_scanning:
  stage: security
  image: 
    name: aquasecurity/trivy:latest
    entrypoint: [""]
  services:
    - docker:24.0.5-dind
  variables:
    # Pas de dépendance directe à Docker socket ici car Trivy scanne l'image remote ou FS
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  script:
    - echo "Scanning Image $IMAGE_TAG..."
    # Scan de sévérité CRITICAL et HIGH. Code de sortie 1 si trouvé (bloque le pipeline)
    - trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress $IMAGE_TAG
    # Génération rapport complet pour artefact
    - trivy image --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json $IMAGE_TAG
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  dependencies:
    - build_image

# --- STAGE: RELEASE ---
push_latest:
  stage: release
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - main

# --- STAGE: DEPLOY ---
deploy_prod:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying to Production Server..."
    - scp docker-compose.prod.yml $SSH_USER@$SSH_SERVER_IP:/opt/dolibarr/docker-compose.yml
    # Commandes SSH pour pull et restart
    - ssh $SSH_USER@$SSH_SERVER_IP "
        cd /opt/dolibarr &&
        export CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE &&
        export CI_COMMIT_TAG=latest &&
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker-compose pull &&
        docker-compose up -d --remove-orphans"
  environment:
    name: production
    url: https://dolibarr.mon-entreprise.com
  only:
    - main
  when: manual 